/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:297ebba3-8e28-4675-be36-ae26a918217a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zHyqz8zj4",
    "aws_user_pools_web_client_id": "2o1n68c2a5rr5o3dh82ek1gqe0",
    "oauth": {}
};


export default awsmobile;
